---
# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/GKECluster/v1beta1@v0.16.0
apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: fosdem-cluster
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: "staging-crossplane-provider-gcp"
  forProvider:
    initialClusterVersion: "1.20"
  writeConnectionSecretToRef:
    name: staging-gke-conn
    namespace: crossplane-system


---
# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/NodePool/v1alpha1@v0.16.0
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: fosdem-nodepool
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: "staging-crossplane-provider-gcp"
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 2
      minNodeCount: 1
    clusterRef:
      name: staging-fosdem-cluster
    config:
      machineType: n1-standard-4
    initialNodeCount: 2
