---
# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/GKECluster/v1beta1@v0.16.0
apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: cluster
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: "dev-crossplane-provider-gcp"
  forProvider:
    initialClusterVersion: "1.19"


---
# API Reference: https://doc.crds.dev/github.com/crossplane/provider-gcp/container.gcp.crossplane.io/NodePool/v1alpha1@v0.16.0
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: nodepool
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: "dev-crossplane-provider-gcp"
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 2
      minNodeCount: 1
    clusterRef:
      name: dev-cluster
    config:
      machineType: n1-standard-4
    initialNodeCount: 2