---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-serviceaccount
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: staging-kubernetes-provider

---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-rolebinding
  namespace: crossplane-system
spec:
  providerConfigRef:
    name: staging-kubernetes-provider

---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-clusterrole
  namespace: crossplane-system
spec:
  forProvider:
    manifest:
      kind: ClusterRole
      metadata:
        name: job-executor
  providerConfigRef:
    name: staging-kubernetes-provider