apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: crossplane-provider-gcp
  namespace: crossplane-system
spec:
  projectID: sai-research

---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: staging-gke-conn
      namespace: crossplane-system
      key: kubeconfig

---
apiVersion: helm.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: staging-gke-conn
      namespace: crossplane-system
      key: kubeconfig