---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-rolebinding
  namespace: crossplane-system
spec:
  forProvider:
    manifest:
      kind: ClusterRoleBinding
      metadata:
        name: job-executor-global
      subjects:
        - kind: ServiceAccount
          name: dev-keptn-job-executor-job-executor-service
  providerConfigRef:
    name: dev-kubernetes-provider

---
apiVersion: kubernetes.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: kubernetes-provider
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: dev-gke-conn
      namespace: crossplane-system
      key: kubeconfig