---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-rolebinding
  namespace: crossplane-system
spec:
  forProvider:
    manifest:
      kind: ClusterRoleBinding
      metadata:
        name: job-executor-global
      subjects:
        - kind: ServiceAccount
          name: dev-keptn-job-executor-job-executor-service
          namespace: keptn
  providerConfigRef:
    name: dev-kubernetes-provider

---
apiVersion: kubernetes.crossplane.io/v1alpha1
kind: Object
metadata:
  name: job-executor-clusterrole
  namespace: crossplane-system
spec:
  forProvider:
    manifest:
      kind: ClusterRole
      metadata:
        name: job-executor
  providerConfigRef:
    name: dev-kubernetes-provider